version: 2
jobs:
  lint:
    docker: &py38
      - image: playpauseandstop/docker-python:3.0.0b0-py38
    steps:
      - checkout
      - run: make install
      - run: make lint-ci

  test36:
    docker:
      - image: playpauseandstop/docker-python:3.0.0b0-py36
    steps:
      - checkout
      - run: mkdir -p test-results/pytest
      - run:
          command: make test-ci
          environment:
            PYTEST_ADDOPTS: --junitxml=test-results/pytest/junit.xml
            TOXENV: py36
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  test37:
    docker:
      - image: playpauseandstop/docker-python:3.0.0b0-py37
    steps:
      - checkout
      - run: mkdir -p test-results/pytest
      - run:
          command: make test-ci
          environment:
            PYTEST_ADDOPTS: --junitxml=test-results/pytest/junit.xml
            TOXENV: py37
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  test38:
    docker: *py38
    steps:
      - checkout
      - run: mkdir -p test-results/pytest
      - run:
          command: make test-ci
          environment:
            PYTEST_ADDOPTS: --junitxml=test-results/pytest/junit.xml
            TOXENV: py38
      - run: make coveralls
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  deploy:
    docker: *py38
    steps:
      - checkout
      - run: make install
      - run: make deploy-ci

workflows:
  version: 2
  ci:
    jobs:
      - lint:
          filters: &all_tags_and_branches
            tags:
              only: /.*/

      - test36:
          requires:
            - lint
          filters: *all_tags_and_branches

      - test37:
          requires:
            - lint
          filters: *all_tags_and_branches

      - test38:
          requires:
            - lint
          filters: *all_tags_and_branches

      - deploy:
          requires:
            - test36
            - test37
            - test38
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
